create table if not exists public.growth_data (
  id bigint generated by default as identity primary key,
  weight numeric(5,2) not null check (weight > 0),
  height numeric(5,2) not null check (height > 0),
  head_circumference numeric(5,2) not null check (head_circumference > 0),
  feeding_type text not null check (feeding_type in ('ASI', 'MPASI', 'makanan')),
  complaints text,
  status text not null check (status in ('normal', 'risk', 'stunting')),
  created_at timestamptz not null default now()
);

create table if not exists public.reminders (
  id bigint generated by default as identity primary key,
  title text not null,
  date date not null,
  status text not null default 'pending' check (status in ('pending', 'done')),
  created_at timestamptz not null default now()
);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  activity text not null,
  duration integer not null check (duration > 0),
  food text not null,
  created_at timestamptz not null default now()
);

create index if not exists growth_data_created_at_idx on public.growth_data (created_at desc);
create index if not exists reminders_date_idx on public.reminders (date asc);
create index if not exists activities_created_at_idx on public.activities (created_at desc);

alter table public.growth_data enable row level security;
alter table public.reminders enable row level security;
alter table public.activities enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert on public.growth_data to anon, authenticated;
grant select, insert, update, delete on public.reminders to anon, authenticated;
grant select, insert on public.activities to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists "Allow public read growth data" on public.growth_data;
create policy "Allow public read growth data"
on public.growth_data for select
using (true);

drop policy if exists "Allow public insert growth data" on public.growth_data;
create policy "Allow public insert growth data"
on public.growth_data for insert
with check (true);

drop policy if exists "Allow public read reminders" on public.reminders;
create policy "Allow public read reminders"
on public.reminders for select
using (true);

drop policy if exists "Allow public insert reminders" on public.reminders;
create policy "Allow public insert reminders"
on public.reminders for insert
with check (true);

drop policy if exists "Allow public update reminders" on public.reminders;
create policy "Allow public update reminders"
on public.reminders for update
using (true)
with check (true);

drop policy if exists "Allow public delete reminders" on public.reminders;
create policy "Allow public delete reminders"
on public.reminders for delete
using (true);

drop policy if exists "Allow public read activities" on public.activities;
create policy "Allow public read activities"
on public.activities for select
using (true);

drop policy if exists "Allow public insert activities" on public.activities;
create policy "Allow public insert activities"
on public.activities for insert
with check (true);
